import { Product } from './types/Product'

export const sampleProduct: Product[] = [
  {
    name: 'Sample Product',
    slug: 'sample-product',
    image: '/images/disc1.jpeg',
    category: 'Sample Category',
    brand: 'Sample Brand',
    price: 50,
    countInStock: 500,
    description: 'Sample Description',
    rating: 3,
    numReviews: 5000,
  },
  {
    name: 'Sample Product 2',
    slug: 'sample-product-2',
    image: '/images/disc2.jpg',
    category: 'Sample Category',
    brand: 'Sample Brand',
    price: 60,
    countInStock: 200,
    description: 'Sample Description',
    rating: 3.5,
    numReviews: 200,
  },
  {
    name: 'Sample Product 3',
    slug: 'sample-product-3',
    image: '/images/disc3.jpg',
    category: 'Sample Category',
    brand: 'Sample Brand',
    price: 82,
    countInStock: 10,
    description: 'Sample Description',
    rating: 4.5,
    numReviews: 5,
  },
  {
    name: 'Sample Product 4',
    slug: 'sample-product-4',
    image: '/images/disc4.webp',
    category: 'Sample Category',
    brand: 'Sample Brand',
    price: 82,
    countInStock: 10,
    description: 'Sample Description',
    rating: 4.5,
    numReviews: 5,
  },
]
